
server:
  port: 8080

spring:
  application:
    name: balance-service
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/payflow_db}
    username: ${DATABASE_USERNAME:payflow_user}
    password: ${DATABASE_PASSWORD:payflow_pass}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    jwt:
      secret: ${JWT_SECRET:dev-secret}

logging:
  level:
    com.payflow: DEBUG
    org.springframework.security: DEBUG
